### ISSUE TITLE
I can't run libd (IndexError: list index out of range)

### ISSUE THREAD

**Issue by jackhan2002** [IIE-LibD/libd#2]
Centos, Python 2.66, Androguard 1.9

Traceback (most recent call last):
  File "libd_v_0.0.1.py", line 852, in <module>
    main(apkname,outputpath,lib_info)
  File "libd_v_0.0.1.py", line 804, in main
    total_lib_dicts, clazz_info = funclibext(apkname, outputpath)
  File "libd_v_0.0.1.py", line 438, in funclibext
    apk_vm_serial = decompile(apkname, outputpath)
  File "libd_v_0.0.1.py", line 50, in decompile
    a = Androguard([apkname])
  File "build/bdist.linux-x86_64/egg/androguard/core/androgen.py", line 99, in /__init/__
  File "build/bdist.linux-x86_64/egg/androguard/core/androgen.py", line 113, in _analyze
  File "build/bdist.linux-x86_64/egg/androguard/core/bytecodes/apk.py", line 191, in __init__
  File "build/bdist.linux-x86_64/egg/androguard/core/bytecodes/apk.py", line 1073, in __init__
  File "build/bdist.linux-x86_64/egg/androguard/core/bytecodes/apk.py", line 1115, in getAttributeValue
  File "build/bdist.linux-x86_64/egg/androguard/core/bytecodes/apk.py", line 1020, in getAttributeValue
  File "build/bdist.linux-x86_64/egg/androguard/core/bytecodes/apk.py", line 691, in getString
  File "build/bdist.linux-x86_64/egg/androguard/core/bytecodes/apk.py", line 755, in getShort2
IndexError: list index out of range

**Comment by jackhan2002** [comment]
I update python to 2.7.11, libd gives the same result.

**Comment by jackhan2002** [comment]
I'm sorry. I used a simple app to test libd again, it exports right result.

**Comment by jackhan2002** [comment]
The authors added a method named get_class() into androguard/core/bytecodes/dvm DalvikVMFormat.

**Comment by salmanee** [comment]
Did you manage to run libD eventually?

**Comment by myGitHubmm** [comment]
> 
> 
> Did you manage to run libD eventually?

I managed to run it!
